### ISSUE TITLE
Add Arm Support to Docker Manifest

### ISSUE THREAD

**Issue by pkxro** [Auditware/radar#1]
![Screenshot 2024-08-30 at 2 23 53 PM](https://github.com/user-attachments/assets/f340b21f-6a17-41e2-8400-a74b4f22a8bc)

There currently does not exist an arm supported Dockerfile in the radar manifest. Needed for users with Apple Arm-based chips and others to run radar locally for manual and pre-commit hook usage.

**Comment by forefy** [comment]
Thanks for raising this @pkxro , we are working on a fix and will update.

**Comment by forefy** [comment]
Problem seems to be fixed (tested on Mac M1)


Container images built to the GHCR seemed to not specify arm based platforms, fixed on https://github.com/Auditware/radar/commit/419c6449b3691949d98d4060c1235c84325c69ec 

To have the fix take affect please pull the latest released images (you can just delete the old ones and reinstall)


Do let us know if the problem persists for some reason!
