### ISSUE TITLE
Radar fails with error 500 error response from API with no additional information

### ISSUE THREAD

**Issue by andreihrs** [Auditware/radar#4]
Logs: 

[i] Copying folder from radar container to a shared docker volume
[i] Successfully copied folder
[i] AST successfully generated for folder
[i] Scan initiated for folder
[e] 500 error response from API

**Comment by forefy** [comment]
Hi @andreihrs , thanks for bringing this to our attention, We can probably solve this by adding more logging information around those areas and try catch the real bug behind this. Leaving open until the improvement is applied.
